classDiagram
  direction TB

  %% ===== MODELO (nucleo) =====
  class Juego {
    -Tablero tablero
    -List~String~ niveles
    -int nivelActual
    -Estadisticas stats
    -List~ObservadorJuego~ observadores
    -GestorUndo gestorUndo
    -EstrategiaPuntaje estrategia
    -CargadorNiveles cargador
    -FabricaElementos fabrica
    -EstadoJuego estadoJuego
    +getTablero() Tablero
    +getEstadisticas() Estadisticas
    +getNivelActual() int
    +hayNivelSiguiente() boolean
    +puedeDeshacer() boolean
    +isPausado() boolean
    +togglePausa() 
    +getPuntaje() int
    +agregarObservador(ObservadorJuego o) 
    +notificarEstadoInicial()
    +moverJugador(Direccion d) 
    +crearMemento() MementoJuego
    +restaurar(MementoJuego)
    +deshacer() 
    +reiniciarNivel() 
    +siguienteNivel() 
    -notificar(EventoJuego) 
    -notificar(EventoJuego.Tipo) 
    -intentarEmpujar(ObjetoJuego, Posicion, Direccion) boolean
  }

  class Estadisticas {
    -int movimientos
    -int empujes
    -int usosUndo
  }

  %% ===== OBSERVER =====
  class ObservadorJuego {
    <<interface>>
    +actualizar(EventoJuego e)
  }
  class EventoJuego{
    -Tipo tipo
    -Tablero tablero
    -Estadisticas estadisticas
    -int nivelActual
    -boolean victoria
    -int puntaje
    +getTipo() Tipo
    +getTablero() Tablero
    +getEstadisticas() Estadisticas
    +getNivelActual() int
    +isVictoria() boolean
    +getPuntaje() int
  }
  class Tipo {
    <<enumeration>>
    INICIO
    MOVIMIENTO
    EMPUJE
    BLOQUEADO
    DESHACER
    REINICIO
    VICTORIA
    PAUSA
    REANUDA
}
  %% ===== CRONOMETRO =====
  class CronometroNivel{
    -Timer Timer
    -segundos int
    -Consumer<Integer> onTick
    +actualizar(EventoJuego e)
    -reiniciar()
    +getSegundos() int
  }
  %% ===== VISTA =====
  class VistaJuego {
    -PanelTablero panelTablero
    -PanelHUD panelHUD
    -victoriaMostrada boolean
    -controlador ControladorJuego
    -CronometroNivel cronometro
    +actualizar(EventoJuego e)
    +setCronometro(CronometroNivel cronometro)
    +actualizarTiempo(int segundos)
    +inicializar(ControladorJuego controlador)
    -mostrarResumenYAvanzar(EventoJuego e)
  }
  class PanelTablero {
    +render(Tablero t)
    +setPausado(boolean pausado)
    #paintComponent(Graphics g)
    -dibujarOverlayPausa( Graphics g)
    -dibujarTerreno(Graphics g, Terreno terreno, int x, int y)
    -dibujarMarcador(Graphics g, String clave, Color fallback, int x, int y)
    -dibujarObjeto(Graphics g, ObjetoJuego objeto, int x, int y)
    -dibujarJugador(Graphics g, Jugador jugador, int x, int y)
    -claveObjeto(ObjetoJuego juego) String
    -dibujarObjetoPorDefecto(Graphics g, ObjetoJuego objeto, int x, int y)
    -dibujarCaja(Graphics g, int x, int y, Color color)
    -colorTerreno(Terreno terreno) Color
  }
  class PanelHUD {
    -JLabel movimientos
    -JLabel empujes
    -JLabel nivel
    -JLabel tiempo
    -JButton btnUndo
    -JButton btnReiniciar
    -JButton btnPausa
    +conectar(ControladorJuego controllador)
    +actualizar(EventoJuego e)
    +actualizarTiempo(int segundos)
    -actualizarLabels(int nivelActual, int movs,int emp)
    
  }

  %% ===== CONTROLADOR =====
  class ControladorJuego {
    -Juego juego
    +keyPressed(KeyEvent e)
    +onUndo()
    +onReiniciar()
    +onTogglePausa()
    +onSiguienteNivel()
    +hayNivelSiguiente() boolean
  }

  %% ===== SINGLETON =====
  class GestorSonido {
    <<Singleton>>
    -GestorSonido instancia$
    +getInstancia()$ GestorSonido
    +actualizar(EventoJuego e)
  }
  class GestorAssets {
    <<Singleton>>
    -GestorAssets instancia$
    +getInstancia()$ GestorAssets
    +getImagen(String clave) Image
    +getSonido(String clave) Clip
  }

  %% ===== MEMENTO (undo) =====
  class GestorUndo {
    -Deque~MementoJuego~ historial
    -int usosConsecutivos
    +guardar(MementoJuego m)
    +deshacer() MementoJuego
    +puedeDeshacer() boolean
    +limpiar()
  }
  class MementoJuego {
    -char[][] estadoTablero
    -Estadisticas estadoStats
    +getEstadoTablero() char[][]
    +getEstadoStats() Estadisticas
  }

  %% ===== STRATEGY (puntaje) =====
  class EstrategiaPuntaje {
    <<interface>>
    +calcular(Estadisticas s) int
  }
  class PuntajeEstandar {
    +calcular(Estadisticas s) int
  }
  class PuntajeConTiempo{
    +calcular(Estadisticas s) int
  }

  %% ===== FACTORY METHOD (carga de niveles) =====
  class CargadorNiveles {
    +cargar(String archivoTxt) Tablero
  }
  class FabricaElementos {
    -Map~Character, CreadorElemento~ charMap
    +crearElemento(char c, Posicion p) ElementoCreado
  }

  %% ===== TABLERO =====
  class Tablero {
    -Celda[][] celdas
    -Jugador jugador
    +getCelda(Posicion p) Celda
    +moverObjeto(Posicion origen, Posicion destino)
    +esVictoria() boolean
  }
  class Celda {
    -Terreno terreno
    -ObjetoJuego objeto
    +estaLibre() boolean
  }

  %% ===== TERRENOS =====
  class Terreno {
    <<abstract>>
    +alEntrar(ObjetoJuego o, Tablero t)*
  }
  class Piso
  class TerrenoResbaladizo {
    +alEntrar() desliza hasta chocar
  }
  class CasillaDestino {
    +tieneCaja() boolean
  }
  class CasilleroCerrojo {
    -List~Muro~ murosAsociados
    +alEntrar() abre muros si CajaLlave
  }

  %% ===== OBJETOS =====
  class ObjetoJuego {
    <<abstract>>
    -Posicion posicion
    +esEmpujable() boolean
    +bloqueaPaso() boolean
  }
  class Jugador {
    +mover(Direccion d)
  }
  class Pared

  %% ===== STATE (muros) =====
  class Muro {
    -EstadoMuro estado
    +setEstado(EstadoMuro e)
    +bloqueaPaso() boolean
  }
  class EstadoMuro {
    <<interface>>
    +puedeAtravesarse() boolean
  }
  class MuroAbierto
  class MuroCerrado

  %% ===== CAJAS =====
  class Caja {
    <<abstract>>
    +alSerEmpujada(Tablero t)
  }
  class CajaNormal
  class CajaFragil {
    -int resistencia
    +alSerEmpujada() resta resistencia
  }
  class CajaLlave

  %% ===== STATE (juego) =====
  class EstadoJuego {
    <<interface>>
    +aceptaAcciones() boolean
  }
  class EstadoJugando {
    +aceptaAcciones() boolean
  }
  class EstadoPausado {
    +aceptaAcciones() boolean
}

  %% ===== RELACIONES: MVC + Observer =====
  VistaJuego ..|> ObservadorJuego
  GestorSonido ..|> ObservadorJuego
  Juego --> ObservadorJuego : notifica
  VistaJuego *-- PanelTablero
  VistaJuego *-- PanelHUD
  PanelTablero ..> GestorAssets : usa
  GestorSonido ..> GestorAssets : usa
  ControladorJuego --> Juego : invoca
  VistaJuego --> ControladorJuego : delega input
  EventoJuego --> Tablero
  EventoJuego --> Estadisticas
  EventoJuego --> Tipo
  CronometroNivel ..|>  ObservadorJuego
  PanelHUD  --|> JPanel
  PanelTablero  --|> JPanel
  VistaJuego  --|> JFrame
  VistaJuego ..|> ObservadorJuego
  ControladorJuego --|> KeyAdapter

  %% ===== RELACIONES: Memento =====
  Juego *-- GestorUndo
  GestorUndo o-- MementoJuego : max 15
  Juego ..> MementoJuego : crea

  %% ===== RELACIONES: Strategy =====
  Juego --> EstrategiaPuntaje
  Juego *-- Estadisticas
  PuntajeEstandar ..|> EstrategiaPuntaje
  PuntajeConTiempo ..|> EstrategiaPuntaje

  %% ===== RELACIONES: Factory + Tablero =====
  Juego *-- Tablero
  Juego ..> CargadorNiveles : usa
  CargadorNiveles ..> FabricaElementos : usa
  CargadorNiveles ..> Tablero : crea
  FabricaElementos ..> Terreno : crea
  FabricaElementos ..> ObjetoJuego : crea
  Tablero *-- Celda : 1..*
  Celda --> Terreno
  Celda --> ObjetoJuego : 0..1

  %% ===== RELACIONES: herencias =====
  Piso --|> Terreno
  TerrenoResbaladizo --|> Terreno
  CasillaDestino --|> Terreno
  CasilleroCerrojo --|> Terreno
  Jugador --|> ObjetoJuego
  Pared --|> ObjetoJuego
  Muro --|> ObjetoJuego
  Caja --|> ObjetoJuego
  CajaNormal --|> Caja
  CajaFragil --|> Caja
  CajaLlave --|> Caja

  %% ===== RELACIONES: State =====
  Muro --> EstadoMuro
  MuroAbierto ..|> EstadoMuro
  MuroCerrado ..|> EstadoMuro
  CasilleroCerrojo ..> Muro : abre
  EstadoPausado  ..|> EstadoJuego
  EstadoJugando ..|> EstadoJuego

  